### ISSUE TITLE
Unable to use xeroClient.callback

### ISSUE THREAD

**Issue by JaredPage** [node-vision/xero-client#2]
The readme currently documents behaviour that's unavailable (as in - not exported) in the current index.js. The function being exported is requestXeroRequestToken. 

You can see the pull request here: #1

**Comment by romanmandryk** [comment]
Hi Jared, thanks for spotting it.
I accidentally replaced it by 3 new methods when doing second release

**Comment by JaredPage** [comment]
Heh no problem!
